title: "Research Methods & Professional Practice Module – E-Portfolio"
description: "MSc Computer Science, UoE Online"
theme: midnight
baseurl: "yy23505.github.io/rmpp-eportfolio-essex"     
url: "https://<yy23505>.github.io"

# Navigation (minima supports header_pages)
header_pages:
  - index.md
  - modules/rmpp.md
  - evidence/index.md
  - reflections/index.md
  - outcomes/index.md
  - ethics/index.md
  - about.md
