title: "Research Methods & Professional Practice Module – E-Portfolio"
description: "MSc Computer Science, UoE Online"
theme: "jekyll-theme-midnight"
baseurl: "yy23505.github.io/rmpp-eportfolio-essex"     
url: "https://yy23505.github.io"

# Navigation (Header Pages)
header_pages:
  - index.md
  - modules/rmpp.md
  - "Collaborative Discussion 1 - Abusive Workplace Behavior/index.md"
  - "Reflective Activity 1 - Ethics in Computing/index.md"
  - "Literature Review/index.md"
  - "Collaborative Discussion 2 - Case Study on Accuracy of Information/index.md"
  - "Inferential Statistics Workshop and Statistics Worksheet/index.md"
  - "Research Proposal/index.md"
  - "Statistical Worksheet Submissions/index.md"

# Optional settings
show_downloads: false
github:
  is_project_page: true
  repository_url: "https://github.com/<your-username>/rmpp-eportfolio-essex"
