title: "Research Methods & Professional Practice – E-Portfolio"
description: "MSc Computer Science (University of Essex Online) – Evidence, reflections, and outcomes"
theme: jekyll-theme-slate
markdown: kramdown

# IMPORTANT for project sites published at /<repo-name>
url: "https://yy23505.github.io"
baseurl: "/rmpp-eportfolio-essex"

# Navigation (Header Pages)
header_pages:
  - index.md
  - modules/rmpp.md
  - "Collaborative Discussion 1 - Abusive Workplace Behavior/index.md"
  - "Reflective Activity 1 - Ethics in Computing/index.md"
  - "Literature Review/index.md"
  - "Collaborative Discussion 2 - Case Study on Accuracy of Information/index.md"
  - "Inferential Statistics Workshop and Statistics Worksheet/index.md"
  - "Research Proposal/index.md"
  - "Statistical Worksheet Submissions/index.md"

show_downloads: false
github:
  is_project_page: true
  repository_url: "https://github.com/yy23505/rmpp-eportfolio-essex"
